baseURL = 'https://syrno.net/'
languageCode = 'en-us'
title = 'syrno.net'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Projects'
    url = '/projects/'
    weight = 2
  [[menu.main]]
    name = 'Links'
    url = '/links/'
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true